export const SET_AUCTION = 'SET_AUCTION ';

export const SET_COMMENTS = 'SET_COMMENTS';
export const CREATE_COMMENTS = 'CREATE_COMMENTS';

export const CREATE_PRICE = 'CREATE_PRICE';
export const GET_MY_AUCTIONS = 'GET_MY_AUCTIONS';
